<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>AtheriosServer</AssemblyName>
    <RootNamespace>AtheriosServer</RootNamespace>
    <Title>Atherios Silver Dedicated Server</Title>
    <Authors>RoboSmash</Authors>
    <Company>RoboSmash</Company>
    <Product>Atherios Silver</Product>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Update="server.properties">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ops.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>