name: Hax SWF Compiler

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: asannou/setup-haxe@v1
        with:
          haxe-version: 4.3.1

      - name: Install Libraries
        run: |
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-addons
          haxelib run lime setup

      - name: Build Flash SWF
        run: |
          haxelib run lime build flash

      - name: Upload atherios-silver.swf
        uses: actions/upload-artifact@v4
        with:
          name: atherios-silver-swf
          path: export/flash/bin/atherios-silver.swf
