name: Hax SWF Compiler

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Haxe & Neko
        run: |
          sudo add-apt-repository ppa:haxe/releases -y
          sudo apt-get update
          sudo apt-get install -y haxe neko

      - name: Install Libraries & Build SWF
        run: |
          mkdir -p ~/haxelib && haxelib setup ~/haxelib
          haxelib install lime --silent
          haxelib install openfl --silent
          haxelib install flixel --silent
          haxelib install flixel-addons --silent
          haxelib run lime setup -y
          haxelib run lime build flash

      - name: Upload atherios-silver.swf
        uses: actions/upload-artifact@v3
        with:
          name: atherios-silver-swf
          path: export/flash/bin/atherios-silver.swf
