name: Build Flash SWF

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: codekaizen/apache-flex-sdk:latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Compile ActionScript to SWF
      run: |
        mxmlc Main.as -output atherios-silver.swf -static-link-runtime-shared-libraries=true

    - name: Upload SWF File Artifact
      uses: actions/upload-artifact@v3
      with:
        name: atherios-silver-swf
        path: atherios-silver.swf
